# Default values for catawiki-playwright-automation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: catawiki-playwright-automation
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

job:
  command:
    - "npx"
    - "playwright"
    - "test"
  env:
    - name: BASE_URL
      value: "https://www.catawiki.com/en"
  backoffLimit: 0