apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "catawiki-playwright-automation.fullname" . }}
  labels:
{{ include "catawiki-playwright-automation.labels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
{{ include "catawiki-playwright-automation.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command:
{{ .Values.job.command | toYaml | indent 12 }}
          env:
{{- range .Values.job.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
  backoffLimit: {{ .Values.job.backoffLimit | default 0 }}